/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* Uart_Printf_SCB_IRQ */
    const cy_stc_sysint_t Uart_Printf_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)Uart_Printf_SCB_IRQ__INTC_NUMBER,
        .intrPriority = Uart_Printf_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* I2C_MAX30105_SCB_IRQ */
    const cy_stc_sysint_t I2C_MAX30105_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)I2C_MAX30105_SCB_IRQ__INTC_NUMBER,
        .intrPriority = I2C_MAX30105_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* isr_1ms */
    const cy_stc_sysint_t isr_1ms_cfg = {
        .intrSrc = (IRQn_Type)isr_1ms__INTC_NUMBER,
        .intrPriority = isr_1ms__INTC_CORTEXM4_PRIORITY
    };

    /* fillBuff_isr */
    const cy_stc_sysint_t fillBuff_isr_cfg = {
        .intrSrc = (IRQn_Type)fillBuff_isr__INTC_NUMBER,
        .intrPriority = fillBuff_isr__INTC_CORTEXM4_PRIORITY
    };

    /* spo2_isr */
    const cy_stc_sysint_t spo2_isr_cfg = {
        .intrSrc = (IRQn_Type)spo2_isr__INTC_NUMBER,
        .intrPriority = spo2_isr__INTC_CORTEXM4_PRIORITY
    };

    /* ADC_INVERTING_AMP_IRQ */
    const cy_stc_sysint_t ADC_INVERTING_AMP_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ADC_INVERTING_AMP_IRQ__INTC_NUMBER,
        .intrPriority = ADC_INVERTING_AMP_IRQ__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

