/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* isr_1ms */
#define isr_1ms__INTC_CORTEXM4_ASSIGNED 1
#define isr_1ms__INTC_CORTEXM4_PRIORITY 7u
#define isr_1ms__INTC_NUMBER 90u
#define isr_1ms_INTC_CORTEXM4_ASSIGNED 1
#define isr_1ms_INTC_CORTEXM4_PRIORITY 7u
#define isr_1ms_INTC_NUMBER 90u

/* spo2_isr */
#define spo2_isr__INTC_CORTEXM4_ASSIGNED 1
#define spo2_isr__INTC_CORTEXM4_PRIORITY 7u
#define spo2_isr__INTC_NUMBER 92u
#define spo2_isr_INTC_CORTEXM4_ASSIGNED 1
#define spo2_isr_INTC_CORTEXM4_PRIORITY 7u
#define spo2_isr_INTC_NUMBER 92u

/* fillBuff_isr */
#define fillBuff_isr__INTC_CORTEXM4_ASSIGNED 1
#define fillBuff_isr__INTC_CORTEXM4_PRIORITY 7u
#define fillBuff_isr__INTC_NUMBER 91u
#define fillBuff_isr_INTC_CORTEXM4_ASSIGNED 1
#define fillBuff_isr_INTC_CORTEXM4_PRIORITY 7u
#define fillBuff_isr_INTC_NUMBER 91u

/* Uart_Printf_SCB_IRQ */
#define Uart_Printf_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define Uart_Printf_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define Uart_Printf_SCB_IRQ__INTC_NUMBER 46u
#define Uart_Printf_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define Uart_Printf_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define Uart_Printf_SCB_IRQ_INTC_NUMBER 46u

/* I2C_MAX30105_SCB_IRQ */
#define I2C_MAX30105_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_MAX30105_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_MAX30105_SCB_IRQ__INTC_NUMBER 47u
#define I2C_MAX30105_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_MAX30105_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_MAX30105_SCB_IRQ_INTC_NUMBER 47u

/* ADC_INVERTING_AMP_IRQ */
#define ADC_INVERTING_AMP_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_INVERTING_AMP_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_INVERTING_AMP_IRQ__INTC_NUMBER 138u
#define ADC_INVERTING_AMP_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_INVERTING_AMP_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_INVERTING_AMP_IRQ_INTC_NUMBER 138u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
